Enqueue
         ::= PUT ( Queue-Limit ( (Enqueued ('200')) | '404' ) )


CheckQueue
         ::= HEAD ( ('X-FIBER-MSG-ID' (IsFound ('200') | '404') ) | (IsNotEpmty ( ('X-FIBER-MSG-ID' ('200') ) | '204')))